<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Privacy Policy') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg p-4">
                <p class="text-white">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet orci eu tellus dapibus iaculis et eget enim. Mauris in mattis quam. Aliquam sit amet ante a erat condimentum malesuada a sit amet lacus. Duis pharetra gravida felis at aliquam. Mauris eleifend eros et nisi facilisis, vitae convallis ante rhoncus. Mauris sit amet justo mauris. Quisque rutrum quam vel enim vehicula, ac pellentesque velit tristique. Suspendisse sodales lobortis rutrum. Nam vitae consequat ex, a bibendum orci. Fusce justo enim, luctus in porttitor in, pulvinar ac mauris. Aliquam erat volutpat.<br><br>

                    Quisque nunc lorem, convallis vel pharetra blandit, ullamcorper vitae risus. Curabitur iaculis erat lorem, sit amet congue leo ullamcorper eu. Maecenas ultricies arcu scelerisque sodales auctor. Sed ut dui felis. Morbi in velit nec leo scelerisque tempor. Integer tortor ligula, bibendum sed molestie et, ultricies finibus turpis. Aliquam at ipsum a risus tincidunt porttitor eu vitae mi. Vestibulum sodales posuere purus, vel porttitor nisl vulputate congue. Vestibulum dolor massa, tincidunt sit amet justo ac, vestibulum congue tortor. Proin lacinia quam a tempus varius.<br><br>

                    Pellentesque efficitur commodo elit, sed tristique erat lobortis sed. Morbi dignissim, felis sit amet condimentum tincidunt, magna quam aliquet ex, eu fringilla est est sit amet nisi. Donec sed commodo ante, sed gravida felis. Suspendisse lectus tellus, posuere ac quam vitae, convallis mollis mi. Duis a ex eget quam fermentum iaculis. Sed non erat ac dolor rutrum viverra quis vitae sapien. Mauris pretium commodo mi sit amet laoreet. Etiam eget vulputate velit. Phasellus sagittis placerat magna eu scelerisque. Mauris semper justo enim, sed elementum nisl accumsan a. Duis elementum turpis massa, id dictum lacus eleifend sed. Phasellus vel facilisis purus, in dictum odio. Nulla pellentesque scelerisque nisi id dictum. Mauris eu felis est. Vestibulum a erat diam.<br><br>

                    Proin eget sapien dignissim, laoreet magna ut, varius arcu. Maecenas bibendum ornare magna. Morbi varius magna ipsum, sed blandit leo elementum in. Proin egestas iaculis velit, commodo pulvinar sapien lacinia in. Nunc quis vulputate nisl, in volutpat dolor. Sed lorem neque, eleifend nec maximus eu, facilisis in orci. Quisque ut libero sed lacus pretium interdum quis sed tortor. Proin sit amet sapien felis. Aliquam id lectus vel nulla pellentesque tristique. Sed nisi mi, semper eu semper blandit, accumsan in massa. Sed nec efficitur lacus. Pellentesque interdum accumsan elementum. Proin ultrices diam neque, at facilisis leo tristique eget.<br><br>

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel elit vitae quam ultrices gravida a non orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis lobortis, mauris non lacinia convallis, mi lorem accumsan velit, eu convallis felis enim eu justo. Proin nunc nisi, tempor vel venenatis ac, rutrum et leo. Donec euismod nibh pulvinar sagittis vestibulum. Quisque ullamcorper, quam a sagittis molestie, dui dolor faucibus magna, non tincidunt tortor risus ac augue. Ut tincidunt venenatis felis, quis euismod mi facilisis in. Donec semper nisl justo, ac consequat sapien posuere sed. Nullam nulla turpis, fringilla nec erat a, consectetur vehicula est. Phasellus placerat massa eget ornare venenatis. Nam egestas nulla condimentum interdum tincidunt. Aliquam auctor viverra ante in facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;<br><br>

                    Cras eu lorem nec arcu suscipit porttitor. Cras augue magna, efficitur quis dapibus eu, molestie ullamcorper ipsum. Vivamus id ultrices leo. Nulla porta, dolor elementum convallis sagittis, odio massa sollicitudin arcu, quis hendrerit turpis arcu eget urna. Sed tristique lectus ut dolor gravida laoreet. Fusce consectetur elementum lorem ac efficitur. Mauris dapibus odio accumsan porttitor fermentum. Etiam ultricies luctus mauris, vel faucibus felis posuere non. Quisque sit amet nunc feugiat, eleifend turpis nec, egestas justo. Aliquam metus purus, molestie quis dictum vel, mattis non sapien. Morbi eget sapien nec erat dignissim dapibus sed nec metus.<br><br>

                    Cras magna arcu, rutrum ut volutpat in, dictum id neque. Aliquam sit amet egestas dolor. Vestibulum congue eu diam in maximus. Donec lacinia urna eu nunc hendrerit, a hendrerit velit hendrerit. Pellentesque accumsan nunc eget erat iaculis commodo. Aenean tristique, magna ut dignissim dignissim, nisi eros feugiat mauris, nec interdum leo lacus a augue. Aliquam lacus magna, volutpat sit amet iaculis ac, tincidunt et ipsum. Integer at dictum leo, sed iaculis lectus. Etiam at congue nibh, ut porttitor urna. In sodales sit amet ante quis porttitor. Maecenas vehicula finibus augue, eu accumsan ex pharetra ultricies. Vestibulum id sem ut mauris varius pretium eleifend tincidunt ligula. Proin at felis tincidunt, porta tortor vitae, scelerisque nisl.<br><br>

                    Praesent at rutrum ex, sit amet eleifend lectus. Aenean id tortor et dui molestie mattis porttitor sed libero. Donec ut mauris erat. Aliquam tincidunt lacinia pulvinar. Maecenas fringilla sapien elit, quis vestibulum lorem scelerisque at. Vestibulum accumsan mi pulvinar ante sollicitudin bibendum. Nam ut pulvinar ante. Maecenas volutpat in nulla eget fermentum. Nam quis gravida dolor.<br><br>

                    Duis consectetur in nunc a egestas. Vestibulum leo urna, lacinia a lectus ac, placerat efficitur nisi. Vestibulum quis ullamcorper eros, vel pretium ligula. Praesent id rhoncus tellus. Aliquam ut elementum massa, non ultrices dui. Aliquam commodo magna eget velit sodales, eu viverra lacus hendrerit. Fusce et enim sem. Aenean vitae bibendum orci. Curabitur ac diam sagittis, auctor turpis eu, accumsan magna. Praesent at mi nec massa euismod auctor eget id sem. Quisque mollis rhoncus arcu eu accumsan. Duis at diam elementum, lacinia nunc at, ullamcorper nibh. Proin a interdum purus, in fringilla nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.<br><br>

                    Maecenas iaculis massa tortor, eget luctus lacus posuere id. Etiam volutpat blandit tellus a porta. Etiam in semper velit, tempor interdum leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis mi metus. Maecenas nec tellus neque. Pellentesque eu maximus velit. Nam eleifend augue nibh, id sollicitudin mauris convallis vel. Integer molestie sapien in ex interdum, eget tincidunt elit placerat. Phasellus rhoncus libero sit amet interdum congue. Fusce ac eros a est dignissim porttitor. Maecenas id varius ante. Curabitur posuere ornare feugiat. Sed venenatis arcu quis nisi auctor tempor.<br><br>

                </p>
            </div>
        </div>
    </div>
</x-app-layout>
